apiVersion: v1
kind: Service
metadata:
  name: argo-cli-service
spec:
  ports:
  - name: argo-cli-port
    port: {{ .Values.argo.containerPort }}
    targetPort: {{ .Values.argo.containerPort }}
  selector:
    app: {{ .Values.argo.name }}
status:
  loadBalancer: {}