apiVersion: v1
data:
  tls.crt: {{ .Files.Get "extra/fullchain.pem" | b64enc }}
  tls.key: {{ .Files.Get "extra/privkey.pem" | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: ingress-secret
type: kubernetes.io/tls
