argo:
  name: python-scaler
  image: <private-registry-hostname>/resource-scaler:latest
  containerPort: 8080

service:
  name: python-scaler

imagePullSecrets: regcred3

ingress:
  enabled: true
  path: /
  # Used to create an Ingress record.
  host: <python-scaler-hostname>
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/secure-backends: “true”
    nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
  labels: {}
  tls:
    secretName: tls-secret
